# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: fuel-plugin-detach-swift
  type: group
  role: [swift_proxy, swift_object]

- id: swift_proxy
  type: puppet
  groups: [fuel-plugin-detach-swift]
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: ""
    timeout: 3600

- id: swift_object
  type: puppet
  groups: [fuel-plugin-detach-swift]
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: ""
    timeout: 3600

#- id: fuel-plugin-detach-swift-post-deployment-sh
#  type: shell
#  role: [fuel-plugin-detach-swift]
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: fuel-plugin-detach-swift-pre-deployment-sh
#  type: shell
#  role: [fuel-plugin-detach-swift]
#  required_for: [pre_deployment_end]
#  requires: [pre_deployment_start]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
