attributes:
  metadata:
    label: "Swift settings"
    weight: 90
  yaml_additional_config:
    type: "textarea"
    weight: 52
    value: |
      #Here put your configuration.
      #Put '#' for comment
      #Don't touch the option if you don't know what is
      #
      #key1=value1
      #key2=value2
    label: "Additional config"
    description: "Just put here valid yaml"
    regex:
      source: '.+'
      error: "This field should not be empty"
  partition_power:
    value: "15"
    label: "Swift partition power"
    description: "Swift partition power used to compute total partition"
    weight: 25
    type: "text"
    regex:
      source: '[1-9][0-9]'
      error: "You must provide a valid number in the range 10:99"
